### ISSUE TITLE
git does not work on OSX.

### ISSUE THREAD

**Issue by ktf** [cms-sw/cmsdist#111]
From @VinInn:

``` bash
pb-d-128-141-131-26:~/CMSSW_7_0_0_pre0/src innocent$ git cms-addpkg DataFormats/Math
No release tags specified, using default CMSSW_7_0_0_pre0.
You are on branch CMSSW_7_0_X
Checking out DataFormats/Math in tag CMSSW_7_0_0_pre0.
Your reference git repository does not seem to exist, would you like to create it? [ y / N / ? ] yCloning into bare repository '/Users/innocent/.cmsgit-cache'...
fatal: unable to access 'https://github.com/cms-sw/cmssw.git/': SSL certificate problem: unable to get local issuer certificate
```

@davidlt Are you sure we have a working curl+openssl on osx? I vaguely remember similar issues with standalone curl, could you check?

**Comment by ktf** [comment]
Workaround for the moment is:

``` bash
export PATH=/usr/bin:$PATH
```

to pick up system git, which does not have the problem.

**Comment by davidlt** [comment]
The problem is understood. On Darwin cURL is modified to use _Keychain_, thus Certification Authority certificates are not available on the system. This does not allow cURL/GIT to verify any HTTPS communication.

We have two options:
1. Add `GIT_SSL_NO_VERIFY=true` which disables HTTPS verification, kinda "trust all" mode.
2. A script is included into cURL library to download from Mozilla (NSS) Certification Authority certificates and generate `ca-bundle.crt`. Such should be shipped with cURL/GIT/different package and  set `GIT_SSL_CAPATH` and/or `GIT_SSL_CAINFO`.

Both work:

```
GIT_SSL_NO_VERIFY=true git clone https://github.com/cms-sw/cms-git-tools.git
GIT_SSL_CAPATH=$PWD GIT_SSL_CAINFO=ca-bundle.crt git clone https://github.com/cms-sw/cms-git-tools.git
```

To be safe I would go w/ **2** and put `ca-bundle.crt` into a GIT package.

**Comment by ktf** [comment]
As discussed, whatever we do should work also with the CERN CA.

**Comment by davidlt** [comment]
Solved for `CMSSW_6_2_0` and above.
