### ISSUE TITLE
New datafiles for FastSimulation/PileUpProducer

### ISSUE THREAD

**Issue by ktf** [cms-sw/cmsdist#205]
The branch:

https://github.com/giamman/cmssw/tree/pileup13tev 

requires new files in:

/afs/cern.ch/cms/data/CMSSW/FastSimulation/PileUpProducer/data

These files are in:

/afs/cern.ch/user/g/giamman/scratch0/fastsim/minbias

we should add these and remove the 14T ones for pre6.

@giamman @davidlt

**Comment by giamman** [comment]
Hi Giulio, did you manage to access the files in my directory /afs/cern.ch/user/g/giamman/scratch0/fastsim/minbias ? I re-checked the permissions, and it looks like user "eulisse" has all that is needed. As an alternative, could I copy to some tmp area of some specific machine, or something like that?

**Comment by davidlt** [comment]
@giamman I cannot access the location. The files should be uploaded into a standard location `/afs/cern.ch/cms/data/CMSSW/FastSimulation/PileUpProducer/data/`, then you can update the list of files in https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_7_0_X/stable/data-FastSimulation-PileUpProducer.spec

**Comment by giamman** [comment]
Yes I know, but I have no permission to write there, so Giulio kindly agreed to do that for me. Unfortunately, he cannot access my directory.
Whom should I ask to get writing permission there?

Thanks,
Andrea

---

Andrea Giammanco
Phone (CERN):    +41 22 76 71567
Mobiles: +41 76 2323672 (CH), +32 497 135121 (BE), +39 349 5552471 (IT)

**Comment by davidlt** [comment]
As I can see the following people have uploaded files to cmsdoc before:
- Florian Beaudette
- Patrick Janot (owner of `FastSimulation/PileUpProducer` on AFS)
- Salavat Abdoulline

**Comment by apfeiffer1** [comment]
Hi Andrea,

   you (should) have permission there now - please let me know if you still
can't upload there.

cheers, andreas

**Comment by giamman** [comment]
Thanks Andreas! It works!
I started copying the files there, and I soon hit the disk quota. 
But I noticed the presence of some very old (April 2007!) files named MinBiasEvents_.root, which are not used since several years as can be seen from the fact that they are not present in FastSimulation/PileUpProducer/data/download.url
Therefore, I propose that I physically delete those files from the directory. (I will not delete the MinBias14TeV_.root files, instead, because that would create trouble for the users of the releases which use them; for example there was a SUSY request for them in June, that entered 53x.)
In addition, I will update FastSimulation/PileUpProducer/data/download.url (or directly https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_7_0_X/stable/data-FastSimulation-PileUpProducer.spec ?) by removing the MinBias14TeV*.root files, so that they will not be shipped with 70x, although still available on the disk.
Does everybody agree on that?

**Comment by apfeiffer1** [comment]
Hi Andrea,

   not sure if deleting things there is a good idea (someone outside may
still need some data there, maybe not now, but in a while when they try to
look again at something specific ... ).

I just increased the space there so you should be able to upload -- let me
know if not.

In general, I fully agree that we need some kind of migration strategy for
the stuff there (and in other "data" directories) -- maybe Giulio et al can
come up with something (move the stuff into another git repo so we have
versioning and archiving ??).

Thanks,
       cheers, andreas

**Comment by davidlt** [comment]
You don't need to touch FastSimulation/PileUpProducer/data/download.url, it's not used.

Just make a pull request for CMSDIST repository with modified data-FastSimulation-PileUpProducer.spec.

david

**Comment by giamman** [comment]
@apfeiffer1 thanks, I copied the files there.
@davidlt Ok, then I will remove FastSimulation/PileUpProducer/data/download.url from the repository, to avoid confusion. Sorry for the ignorance, how do I checkout a file from CMSDIST?

**Comment by davidlt** [comment]
@giamman fork [CMSDIST](https://github.com/cms-sw/cmsdist) repository. Clone it locally, modify the file, push  it your forked repository, and make a pull request.

```
git clone git@github.com:giamman/cmsdist.git cmsdist-giamman
cd cmsdist-giamman
git checkout IB/CMSSW_7_0_X/stable
vim data-FastSimulation-PileUpProducer.spec
git commit -a -s 
# Remember to provide meaningful message.
# Example:
# Removal of X and addition of Y (subject line)
# (empty line)
# X was removed due to ... Y was added instead...  (detailed description of you changes, paragraph). 
# -s option of commit adds your signature to the commit
git push origin HEAD:13Tev-update-data-FastSimulation-PileUpProducer
# Now on GitHub you can make a pull request to official CMSDIST repository
```

**Comment by giamman** [comment]
Thanks, done:
https://github.com/cms-sw/cmsdist/pull/219

---

Andrea Giammanco
Phone (CERN):    +41 22 76 71567
Mobiles: +41 76 2323672 (CH), +32 497 135121 (BE), +39 349 5552471 (IT)

**Comment by giamman** [comment]
@davidlt 
By the way, I am trying to apply the same recipe for 6_2_X (I only changed git checkout IB/CMSSW_7_0_X/stable into git checkout IB/CMSSW_6_2_X/stable) but I see that the content of data-FastSimulation-PileUpProducer.spec is just:

<pre>
### RPM cms data-FastSimulation-PileUpProducer V04-05-18
## IMPORT data-rpm-build
</pre>

instead of the full list of files.
How should I proceed, then?

Thanks in advance,
Andrea

**Comment by davidlt** [comment]
@giamman `CMSSW_6_2_X` replace it with the `data-FastSimulation-PileUpProducer.spec` from `CMSSW_7_0_X`.

**Comment by davidlt** [comment]
Closing. It's merged into `CMSSW_6_2_X` and `CMSSW_7_0_X`.
