### ISSUE TITLE
cms-externals/UTM - transverse mass and di-object-pT

### ISSUE THREAD

**Issue by rekovic** [cms-sw/cmsdist#3071]
@davidlange6 @smuzaffar

Request of UTM external library update as originally posted in the following issue
https://github.com/cms-l1t-offline/cmssw/issues/544.
It provides support for L1T algorithms with transverse-mass and di-object-pT.

For 92X, please use the tag utm_0.6.3 at https://gitlab.cern.ch/cms-l1t-utm/utm.

**Comment by smuzaffar** [comment]
done here https://github.com/cms-sw/cmsdist/pull/3072

**Comment by smuzaffar** [comment]
@rekovic , new tag failed to build because of missing BOOST dependency. see @mrodozov  comment here https://github.com/cms-l1t-offline/cmssw/issues/544#issuecomment-304624332
Can you please follow with utm developers to fix it and provide a new tag.

**Comment by rekovic** [comment]
@bernhard.arnold@cern.ch, @johannes.wittmann@cern.ch, 
Please address the comments above.

**Comment by rekovic** [comment]
@smuzaffar 
Please consider the new UTM tag with the fixes for BOOST dependancy included (thanks @mrodozov).
https://gitlab.cern.ch/cms-l1t-utm/utm/tree/utm_0.6.4

**Comment by smuzaffar** [comment]
@rekovic, is there any cmssw PR which should be tested with new utm library? We get build errors for cmssw see build logs here https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3072/20201/build.log

**Comment by davidlange6** [comment]
Hi @rekovic
a solution is needed today if you want this in for the next running period..

**Comment by rekovic** [comment]
Hi @davidlange6.
Making now a PR which fixes this. Thanks.

**Comment by rekovic** [comment]
@smuzaffar @davidlange6 
Please test it with https://github.com/cms-sw/cmssw/pull/19067

**Comment by smuzaffar** [comment]
thanks @rekovic . @mrodozov has already started the tests.

**Comment by smuzaffar** [comment]
@arnobaer and @rekovic , looks like new utm version does not compile with gcc 630 and gcc700. 
see the build logs here https://cmssdt.cern.ch/SDT/jenkins-artifacts/build-any-ib/CMSSW_9_2_X_2017-06-01-2300/slc6_amd64_gcc630/39746/external/utm/utm_0.6.4/log

gcc 630 and 700 IBs are failing due to this and CMSSW_9_2_1 relase also failed to build for these archs. Can you please provide a fix as soon as possible.

**Comment by rekovic** [comment]
I am contacting developers, right now.  I am sorry about this.

**Comment by smuzaffar** [comment]
@davidlange6 , should we revert this (along with cmssw change) in 92X to get gcc 630/gcc700 IBs working again?

**Comment by davidlange6** [comment]
yes, i will in a few hours (so in time for the 2300 IB)

**Comment by smuzaffar** [comment]
Looks like boost is messing up with the std namespace. Just rearranging the code I was able to build utm for gcc530/630 and 700. A patch is available here https://github.com/cms-sw/cmsdist/blob/utm-064-gcc640-fix/utm-0.6.4-boost-and-transform-fix.patch

@rekovic and @arnobaer,  UTM developers should look in to it.

@davidlange6 , we can get this patch in next IBs to get them working again or wait for proper fix from UTM developers.

**Comment by rekovic** [comment]
@smuzaffar Thanks!

Moving the include of boost and placing methods in the namespace seems ok with me.
@arnobaer, please make sure the rest of your code runs fine with this.

**Comment by smuzaffar** [comment]
We might not need this patch. I remember we had to set -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE for externals depending on boost. Let me try with the flags to see if we can avoid this patch.

**Comment by smuzaffar** [comment]
setting -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE did not help

**Comment by arnobaer** [comment]
Hi, we fixed the issue by passing function objects instead of plain C functions to the STL algorithms, that works well and straight forward for all gcc 530/630/700 compilers (tested on lxplus), see [diff](https://gitlab.cern.ch/cms-l1t-utm/utm/commit/343485d8c035b28e972e99cc8f8e72a087032b54#44cf354d137c69b6552bd88506fefa7476e3aa23_30_30)

Please use utm tag 0.6.5, see https://gitlab.cern.ch/cms-l1t-utm/utm/tree/utm_0.6.5

**Comment by smuzaffar** [comment]
thanks. trying 0.6.5 now
