### ISSUE TITLE
Cache issues w/ tensorflow builds

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#4346]
It looks like a recent change has broken the cache location configuration of tensorflow (or more likely bazel). I noticed as it filling my home directory quota and then the build fails..

cd ~/.cache/bazel/_bazel_dlange/install

[dlange@cmsdev14 install]$ du -s *
108089	31c59cc39bf4dfebb74ed548f6c8b8a1
4	41548cbd1ebbc3ba6936065a7fbb3669
108089	914388969a9cfcfb78d6d8ab3430fc2c
108089	983dba4481d7c0e8c0b0d7ada3594f23
32772	a12181a2af7afc7fab652ddeb129d18c.tmp.26822
142816	cce06be6be2aaaac8be470738dbad99c

@mrodozov

**Comment by mrodozov** [comment]
The default cache dir can be over written with the --output_base option
bazel --output_base=/tmp/bazel/output build x/y:z
described here: https://docs.bazel.build/versions/0.21.0/output_directories.html 
We might explicitly add the option and move the cache to /tmp or elsewhere, in the tf update PR that is still open.
I'm closing this since we have solution for it.
