### ISSUE TITLE
Add pycuda to the CMSSW externals 

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmsdist#4568]
We have got in https://docs.google.com/spreadsheets/d/1tzWPD4NegGvc-LM0iX_4eZu2FZWgbmzOXDE-kq5SAXc/edit#gid=2018532269 the request by @fwyzard to add pycuda to the externals list. As far as I can see in https://pypi.org/project/pycuda/ this is compatible also with python3, so this should not technically create issues with the migration managed by @davidlange6 .

Andrea, could you please clarify the expected use of the package? Are you planning to manage CUDA libraries through python configurations? If I am not wrong this package is not yet used in cms-sw/cmssw#25353 , am I correct?

**Comment by davidlange6** [comment]
pycuda would be useful for a lot of reasons assuming we can hook it to useful gpus in some generic way - might be trivial for @mrodozov to do?

in general you only need to worry about HEP packages not supporting python3 - most of the rest of the world has moved on...

**Comment by fwyzard** [comment]
I would like to use `pycuda` to access the CUDA libraries without the need to compile some external binaries. Two use cases I have so far:
  - list the GPU capabilities, to set up scram's `cuda.xml` accordingly;
  - list the number and type of GPUs, to automatically scale the number of jobs when running benchmarks.

Indeed I am not using it in cms-sw/cmssw#25353 yet, since the use cases are not urgent I would rather wait until it is available in the official builds.
