### ISSUE TITLE
Include Rucio client and python library in CMSSW

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cmsdist#4856]
Original mail: CMS will be slowly moving to Rucio as a DM system. There is a command line and python library client which I’d like to get into CVMFS. How can we go about this and having it accessible to users? In some sense it’s like the DAS Go client, but it is not statically linked.

It is easily installed with “pip install rucio-clients” but I don’t know if that’s possible because of requirement collisions.

Also, there is a config file that I need to supply and an environment variable that would be pointed to it.

**Comment by ericvaandering** [comment]
From @smuzaffar : " Just like DAS go client, we can add it as cmssw external and then it will be deployed via cmssw in cvmfs.

  For setting the env for config file, I would suggest that  we add a rucio-clinet wrapper ( just like dasgo client e.g /cvmfs/cms.cern.ch/common/dasgoclient ) which can set the environment and run the actual rucio client executable. As wrapper is always going to pick the latest version of rucio-clinet executable, so environment can always point to latest config too. Does this sound reasonable?
"

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@ericvaandering , I did a quick build of rucio client and it brings in following[a] dependencies and it only builds for `python2`. 

Should we make it available only under CMSSW env  (i.e. one has to do cmsenv to get it in PATH)? Or would you like it to behave like dasgoclient (i.e. available in cms env by default) and set its own environment. 

As you know , cmssw python makes use of PYTHON27PATH env variable instead of PYTHONPATH, so I am afraid rucio will break if any of the tools in [b] are available via PYTHONPATH in user env.

COMP packages only build for PYTHON2 and use PYTHONPATH, so I would suggest that we build rucio client in comp repo and directly deploy on cvmfs instead of packaging it via cmssw.

[a]
argcomplete==1.9.5
boto==2.49.0
bz2file==0.98
dogpile==0.2.2
dogpile-core==0.4.1
dogpile-cache==0.7.1
kerberos==1.3.0
progressbar==2.5
pykerberos==1.2.1
python-magic==0.4.15
python-swiftclient==3.7.0
requests-kerberos==0.12.0
tabulate==0.8.3

[b]
py2-rucio-clients
py2-requests-kerberos
py2-python-swiftclient
py2-dogpile-cache
py2-tabulate
py2-python-magic
py2-progressbar
py2-nose
py2-kerberos
py2-dogpile-core
py2-dogpile
py2-bz2file
py2-boto
py2-argparse
py2-argcomplete
py2-cryptography
py2-pykerberos
py2-futures
py2-decorator
py2-requests
py2-cffi
py2-ipaddress
py2-enum34
py2-asn1crypto
py2-urllib3
py2-six
py2-pycparser
py2-chardet
py2-certifi
py2-idna
py2-setuptools

**Comment by ericvaandering** [comment]
I think treating it like DAS is the way to go. It sounds like that's easier. I guess I can see an instance where someone may want to mix FWLite and the Rucio python bindings, but let’s cross that bridge when we come it it. It may be easier when everything is Python3 as well.

**Comment by smuzaffar** [comment]
@ericvaandering , as discussed, I did a test install (using `pip`) under /cvmfs/cms-ib.cern.ch/rucio. rucio config I deployed is from our COMP cmsdist repo https://raw.githubusercontent.com/cms-sw/cmsdist/comp_gcc630/rucio-config.file. It runs at least I can run `rucio --version`. Please try it and let me know if this looks good to you. You can just run 
```
source /cvmfs/cms-ib.cern.ch/rucio/setup.sh
```
in bash SHELL to get it in your environment.

The install and env setup scripts are available here https://github.com/cms-sw/cms-bot/tree/master/rucio
If this looks good then we can ask Bockjoo to install it under /cvmfs/cms.cern.ch/rucio

**Comment by smuzaffar** [comment]
@ericvaandering  rucio-client 1.20.0 is now available under /cvmfs/cms-ib.cern.ch/rucio , can you please test this installation and let me know if this works as expected? We can then request Bockjoo to takecare of it under /cvmfs/cms.cern.ch/rucio

**Comment by ericvaandering** [comment]
It works with a change to the config file in etc/rucio.cfg. Some of this is new hosts, but some is changed parameters to work with a proxy. This is not the final hostname, but it's as good as we have right now.

```
-bash-4.2$ cat $RUCIO_HOME/etc/rucio.cfg 
# Copyright European Organization for Nuclear Research (CERN)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Vincent Garonne, <vgaronne@gmail.com>, 2017
# - Eric Vaandering, <ewv@fnal.gov>, 2018

[common]
[client]
rucio_host = http://cms-rucio-testbed.cern.ch
auth_host = https://cms-rucio-auth-testbed.cern.ch
auth_type = x509_proxy
ca_cert = /etc/grid-security/certificates/
request_retries = 3
```

**Comment by ericvaandering** [comment]
This all works fine. Can we get it moved out of IB status and put into the "real" place?

**Comment by ericvaandering** [comment]
@smuzaffar ?

**Comment by smuzaffar** [comment]
@ericvaandering , as discussed in private emails last month, rucio client 1.20.0 is available under /cvmfs/cms.cern.ch/rucio . Please `source /cvmfs/cms.cern.ch/rucio/setup.sh` to try it out.

**Comment by ericvaandering** [comment]
Ah. I must have missed that. I was away on vacation and had a slew of e-mail, so it probably slipped through. Thanks!

**Comment by ericvaandering** [comment]
OK, it works. 

How do we keep this updated? Is there an automatic way to do it (e.g. Rucio is now up to 1.20.2) or do we request it each time or... ?

Do you want to close this ticket?

**Comment by smuzaffar** [comment]
@ericvaandering , for now we have to ask Bockjoo Kim for every version we want to deploy. I would suggest to close this issue and open one for every new vesion we want.

**Comment by ericvaandering** [comment]
Closing
