### ISSUE TITLE
Backport LHAPDF 6.2.1 to 10_2_X and 9_3_X

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmsdist#5009]
@fabiocos @mkirsano @alberto-sanchez  @efeyazgan

Recently several new PDF sets have been added,  
         https://github.com/cms-sw/cmsdist/pull/4927/files
including 
        325300 NNPDF31_nnlo_as_0118_mc_hessian_pdfas   
        325500 NNPDF31_nnlo_as_0118_nf_4_mc_hessian     
and some W-mass related requests.

We would like to know whether we can backport these to 10_2_X and 9_3_X, thus one can use SL6 based cmsconnect (currently based on SL6 but not SL7) to generate UL gridpacks (recommended to use 325300/325500)
https://github.com/cms-sw/genproductions/issues/2238 

However, we notice in #4245  with the concern of backward compatibility, as some other PDF sets can be changed  due to different version number.

We would like to hear your suggestion how to move on. E.g. should we only backport those new PDF sets?

**Comment by fabiocos** [comment]
@qliphy sorry, what is the real target here? To provide samples based on these new PDFs for older productions? Or to produce gridpacks for SL7 releases in SL6 because some procedure was not yet adapted? I understand the latter, and honestly I do not like it.
The move to SL7 was discussed for a long time, and we were investigating possible issues one year ago. I believe that we should do the best to move the production to SL7, instead of backporting new things to old releases (which is just a way to stick on SL6).
Do we have some fundamental problem in running gridpacks on SL7 resources? Or is it just a matter to adapt a few scripts?

**Comment by qliphy** [comment]
@fabiocos  Thanks for the comments.  Yet, I was thinking to produce gridpacks in SL6 for SL7.  I understand your concern.  However, we will discuss a bit more next week inside GEN group to check more on the need for this backup.

A good news is that cmsconnect has now been updated to support SL7 and is being tested [1].


[1] https://github.com/cms-sw/genproductions/issues/2238

**Comment by mkirsano** [comment]
@fabiocos Fabio, if we create a special version of PDF sets where only 
several new sets are added, others are unchanged, will you agree to 
update lhapdf to this sets version in several old CMSSW releases?

31/05/19 12:20, Fabio Cossutti пишет:

**Comment by smuzaffar** [comment]
done
- 9.3.X: https://github.com/cms-sw/cmsdist/pull/5049
- 10.2.X: https://github.com/cms-sw/cmsdist/pull/5028
