### ISSUE TITLE
Missing libraries in scram tools

### ISSUE THREAD

**Issue by bfonta** [cms-sw/cmsdist#5162]
I have noticed that the ```ROOTDataFrame``` and ```ROOTVecOps``` libraries do not currently have a corresponding tool available for scram. I suspect this is as well the case for other relatively new libraries. I therefore ask for a ```root-toolfile.spec``` update.

**Comment by mrodozov** [comment]
Hi there, would you please share the code you were trying to compile yesterday (and against which IB you were testing it) ? 
I'm adding the libs and I want to try if the new toolfile will work with/without the changes (to repeat what you described in the mail exchange for testing)
Thanks in advance

**Comment by bfonta** [comment]
I was using CMSSW_10_6_0 and you can find the code [here](https://github.com/b-fontana/HGCal/tree/master/AnalysisCode). Note that to reproduce the error you will have to remove

`<lib name="ROOTDataFrame"/>`
`<lib name="ROOTVecOps"/>`

from both `AnalysisCode/BuildFile.xml` and `AnalysisCode/bin/BuildFile.xml`.

**Comment by mrodozov** [comment]
alright it works with the new tool file called rootdataframe
didn't work when I removed the two libs (its all in check)
You need to include this 
`<use name="rootdataframe"/>`
which also includes rootvecops to your BuildFile
Also, with the release you use (10_6) in order to work I'll have to backport it to 10_6 (the default goes only to 11_0_X)

**Comment by bfonta** [comment]
Thank you.
I suspect there are other libraries missing from the tools, although I did not check. I think it would be better to do this systematically (maybe automatically) for all new libraries. Otherwise, other people will inevitable post requests similar to this one.

**Comment by mrodozov** [comment]
I can think of something, concerning ROOT, because that's an issue, yes. Maybe we were doing it but I'm not doing it, I'll try to check for new things whenever we update ROOT (which is each week). For auto check it wont be straightforward because we have a policy of "being careful what's included/deployed"
