### ISSUE TITLE
External request: CalibTracker/SiPixelESProducers/data

### ISSUE THREAD

**Issue by hidaspal** [cms-sw/cmsdist#554]
I would like to create an external for CalibTracker/SiPixelESProducers/data as proposed ny slava77 in the pull request discussion:
https://github.com/cms-sw/cmssw/pull/3236

Cheers,
Pal

**Comment by ghost** [comment]
Hi Pal,
I'll take care of this asap. I'll include the 4 *.out files that appears in your PR inside data directory.

**Comment by slava77** [comment]
More details:
the external exists already,
the new files should be added:
- CalibTracker/SiPixelESProducers/data/generror_summary_zp0030.out
- CalibTracker/SiPixelESProducers/data/generror_summary_zp0031.out
- CalibTracker/SiPixelESProducers/data/template_summary_zp0030.out
- CalibTracker/SiPixelESProducers/data/template_summary_zp0031.out
  Pal, you will need to provide the location of the files on afs or elsewhere so that the cmsdist developers can pick it up.

Nominally, the file URLs should be listed in CalibTracker/SiPixelESProducers/data/download.url once they are actually put there on cmsdoc
@degano @ktf is  the download.url  actually used by the distribution system?

**Comment by ghost** [comment]
Hi @slava77, I took the new files from the PR in cmssw, no need to provide them otherway.
I also included the old files.
I'll let you know when the PR to cmsdist will be merged.

**Comment by ghost** [comment]
Hi @slava77 @hidaspal, done in #555.
