### ISSUE TITLE
question on crab client deployment in IB

### ISSUE THREAD

**Issue by belforte** [cms-sw/cmsdist#6393]
Hi @smuzaffar I made a chance to crabclient  etc/crab-bash-completion.sh (added one command) 
but somehow this is merged, but not used. When I do
export PATH=/cvmfs/cms-ib.cern.ch/latest/common:$PATH 
and then use crab-dev
the proper autocompletion is not picked up, i.e. it appears to use the "usual old one",
only after I do 
`source /cvmfs/cms-ib.cern.ch/nweek-02654/share/cms/crab-dev/v3.201104.00/etc/crab-bash-completion.sh`
is the new  `crab-dev crea<TAB>` working

Is this something that will go away by itself, or should I do something ?

**Comment by smuzaffar** [comment]
@smuzaffar , in order to use crab from cms-ib area, you need to `source /cvmfs/cms-ib.cern.ch/latest/cmsset_default.sh` . cmsset_default.sh sources scripts from /cvmfs/cms-ib.cern.ch/latest/share/etc/profile.d (e.g. S99crab-env.sh) which is responsible for setting the proper tab completion. Just setting PATH is not going to sources S99crab-env.sh :-)

**Comment by belforte** [comment]
thanks. Sorry if in the past I had wrongly understood differently.
I will fix my documentation accordingly :-)
