### ISSUE TITLE
Weight storage in P8.303

### ISSUE THREAD

**Issue by agrohsje** [cms-sw/cmsdist#6688]
P8.303 has modified handling of weights. Variables changed definition and needs adjustments: 
                                                                 8.302    8.303
fMaterGen->info.nWeights()                         1       1
fMaterGen->info.weight()                     25248.6.. 25248.6..
fMaterGen->info.numberOfWeights()           1         0
fMaterGen->info.weightValueByIndex(0)  25247.6.. N/A

There is a new option "doSuppressAUXweights". There seems a problem to read in LHE weights. 
@mkirsano @SiewYan : This is the issue we discussed on Skype so we can centrally follow-up. Thanks.

**Comment by agrohsje** [comment]
assign generators

**Comment by mkirsano** [comment]
I started to look, but there is not enough information. What is the configuration and lhe file that don't work? How do you see that the weights are not properly handled?

**Comment by menglu21** [comment]
Hi,
i did a check on request https://cms-pdmv.cern.ch/mcm/requests?prepid=TSG-Run3Winter21wmLHEGS-00001&page=0&shown=127, using the nanogen instead of the full simulation chain, the number of the PS weight seems fine, 89 for each event, but seems most of the PSweights are 1 which i'm not sure it's fine. you can check the fragment and configure file at https://melu.web.cern.ch/melu/WJets/, plot weight.png using 3417 events, and weight2.png are those with weights in (0.9,1.1)

**Comment by smuzaffar** [comment]
@agrohsje do we need to keep this issue open here? Better to open an issue on cms-sw/cmssw to discuss.

**Comment by agrohsje** [comment]
Hi @smuzaffar . Further checks are on my todo list but my recent tests were all fine, no problems. I agree with closing.

**Comment by agrohsje** [comment]
+generators
