### ISSUE TITLE
Create test variant of SIM using static build of Geant4

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#780]
In the case of standalone Geant4 usage of static build of Geant4 and its application bring benifit in CPU about 20%.

For CMSSW GEN-SIM step Geant4 is used by following list of sub-packages:

SimG4CMS/Calo/
SimG4CMS/FP420/
SimG4CMS/Forward/
SimG4CMS/Muon/
SimG4CMS/Tracker/
SimG4Core/Application/
SimG4Core/CustomPhysics/ 
SimG4Core/Generators/
SimG4Core/Geometry/
SimG4Core/HelpfulWatchers/
SimG4Core/MagneticField/
SimG4Core/Notification/
SimG4Core/Physics/
SimG4Core/PhysicsLists/
SimG4Core/SensitiveDetector/
SimRomanPot/SimFP420/

For feasibility check we need to organise one "global" sub-package, let say SimG4Core/Simulation which will include all files from these 16 sub-packes.

**Comment by ktf** [comment]
For the record, we are discussing this also in hypernews at:

https://hypernews.cern.ch/HyperNews/CMS/get/code-perf/739/1.html

Needs cms-sw/cmssw#4416 in order to avoid to avoid bringing in RecoRomanPot in the big plugin.
@smuzaffar is working on scram support to avoid physically merging the packages.

**Comment by civanch** [comment]
It is working fine for 7_2_X and validation 7_2_0_pre3 is going smoothly, so can be backported to 7_1_X.

**Comment by civanch** [comment]
This is implemented as "big plugin" mechanism in 7_1_X and 7_2_X, so it can be closed.
