### ISSUE TITLE
Install pacparser python module

### ISSUE THREAD

**Issue by DrDaveD** [cms-sw/cmsdist#8098]
The pacparser.spec file here currently does `make install` which installs the C-based pacparser library.  It would be helpful if it would also do `make install-pymod` as suported by its [Makefile](https://github.com/manugarg/pacparser/blob/master/src/Makefile).  We would like it to be able to then be imported into python from the cms-sw environment with `import pacparser` so we can do things like is shown in the [pacparser python example](https://github.com/manugarg/pacparser/blob/master/examples/pactest.py).

@stlammel was asking me yesterday how to parse a proxy auto config file for a SAM test, and I think this would be the easiest way for him to do it.

If it's not too hard to teach someone how to test this, @edytuk could implement it.  I am assuming the PR would be made against the current default branch of this repository.  I see that @aandvalenzuela (hi, Andrea!) has submitted PRs here, maybe she could teach @edytuk how to do it.

**Comment by smuzaffar** [comment]
@DrDaveD , https://github.com/cms-sw/cmsdist/pull/8099 should include the python module of pacparser

**Comment by DrDaveD** [comment]
Awesome, thanks a lot Shazad.  It looks like it would have been difficult for someone else to figure out all the details.

**Comment by smuzaffar** [comment]
@DrDaveD,  normally it is easy to update the build receipe if the build system of the package works :-) For pacparser, `make install-pymod` was not enough as the build system is broken (see https://github.com/manugarg/pacparser/pull/137) and it was trying to install the python module in the `python` directory instead of its own. So yes, it was not a trivial update :-)
