### ISSUE TITLE
mpfr-static is obsolete and inconsistent with version in gcc

### ISSUE THREAD

**Issue by VinInn** [cms-sw/cmsdist#8713]
for gcc 12 the version is
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/mpfr-static/4.1.0-a2471f3c8bae8b4325e50ef9aeb7d0eb
while in gcc itself one finds

```
ls  /cvmfs/cms.cern.ch/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/*mpfr*
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/libmpfr.so    /cvmfs/cms.cern.ch/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/libmpfr.so.6.2.0
/cvmfs/cms.cern.ch/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/libmpfr.so.6
```

please provide the same version (6.2.0) for mpfr-static

**Comment by smuzaffar** [comment]
@VinInn , I think the `libmpfr` library version depends on the `gmp` version. For `gcc` build, we use [mpfr version 4.2.0](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_3_X/master/gcc.spec#L16) but as `mpfr` uses `gmp` which  has version [6.2.1](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_3_X/master/gcc.spec#L15) so that is why `libmpfr` ends up with version `6.2`

Currently the `mpfr-static` to uses `4.1.0`, I have updated it to match the version used by `gcc` (https://github.com/cms-sw/cmsdist/pull/8714)

**Comment by smuzaffar** [comment]
@VinInn , look like `mpfr-static` is not used in cmssw. It was needed by `cgal`  which was [dropped from cmssw distro](https://github.com/cms-sw/cmsdist/pull/7284) couple of years ago. Do you have any use of it ? otherwise I can drop both  `mpfr-static` and `gmp-static` packages from cmssw distro

**Comment by VinInn** [comment]
I can live with the dynamic libraries provided by gcc...
